### ISSUE TITLE
Switch visibility

### ISSUE THREAD

**Issue by SillyV** [BeppiMenozzi/TriStateToggleButton#1]
When changing the visibility of the view from Gone or Invisible to Visible while in the middle position the view spot jumps to the wrong position.

![image](https://cloud.githubusercontent.com/assets/13265719/23235288/a07fc08a-f95d-11e6-8b2c-847394d4855c.png)

the green toggles are set to mid.

**Comment by BeppiMenozzi** [comment]
I'll check it as soon as possible, thank you :)

**Comment by SillyV** [comment]
btw, your library is great and it was exactly what I was looking for, thanks for making it public. let me know if you want the xml or the source code in case you can't reproduce the issue. 

I actually worked around this with a hacky solution that used the global layout listener to manualy fix this.  

sadly I'm not savvy enough in all those things to branch and fix and stuff like that

**Comment by BeppiMenozzi** [comment]
It should be corrected... man what a stupid error :) Declared a variable and never defined it :(
I close the issue, but I'd be greateful if you could test it. Just change version from 1.1.2 to 1.1.3
If your app is on the market, and if you can do it, would you let me know which one it is? :)

**Comment by SillyV** [comment]
The app is not on the market yet (I'll leave a comment if i'll decide to publish it) it's just a small app I'm doing mostly for personal use. 
here is the repository if you're curious.. tho I need to commit some updates to it.
https://github.com/SillyV/CounterLists

about the issue. I think it is mostly resolved. but I think it is slightly offset to the end side, 

instead of this line: `spotMidX = (startX + endX) / 2 + borderWidth;`
I would do the following:

`spotMidX = (startX + endX) / 2;`
or maybe even `spotMidX = (startX + endX) / 2 - borderWidth;`

here is what it is like now:

![image](https://cloud.githubusercontent.com/assets/13265719/23555772/da92518a-0032-11e7-84fd-591a1bff7b97.png)

the top switch I played with the visibility, and the bottom switch I didn't.

cheers.

**Comment by BeppiMenozzi** [comment]
I guess you are right, borderWidth shouldn't appear in the calculation, because it's the margin.

**Comment by BeppiMenozzi** [comment]
Anyway I should rewrite this lib when I can. It was the first I made and was a modification on others' libs, so it's a little bit messy. :/

**Comment by SillyV** [comment]
awesome this worked great thanks!
